/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ry_etterna_msd_MinaCalc */

#ifndef _Included_com_ry_etterna_msd_MinaCalc
#define _Included_com_ry_etterna_msd_MinaCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ry_etterna_msd_MinaCalc
 * Method:    getDefaultMSDFor
 * Signature: ([I[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_ry_etterna_msd_MinaCalc_getDefaultMSDFor
  (JNIEnv *, jclass, jintArray, jfloatArray);

/*
 * Class:     com_ry_etterna_msd_MinaCalc
 * Method:    getMSDForRateAndGoal
 * Signature: ([I[FFF)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_ry_etterna_msd_MinaCalc_getMSDForRateAndGoal
  (JNIEnv *, jclass, jintArray, jfloatArray, jfloat, jfloat);

/*
 * Class:     com_ry_etterna_msd_MinaCalc
 * Method:    getMSDForAllRates
 * Signature: ([I[FLjava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_ry_etterna_msd_MinaCalc_getMSDForAllRates
  (JNIEnv *, jclass, jintArray, jfloatArray, jobject);

/*
 * Class:     com_ry_etterna_msd_MinaCalc
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ry_etterna_msd_MinaCalc_dispose
  (JNIEnv *, jclass);

#ifdef __cplusplus
}

#endif
#endif
